---
title: "Seattle"
author: "Lars Almquist"
date: "4/30/2021"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r include=FALSE, warning=FALSE, message=FALSE}
library(osmdata)
library(tidyverse)
sea <- getbb("Seattle, WA")
sea

min_lon <- -122.43940
max_lon <- -122.22089
min_lat <- 47.48123
max_lat <- 47.73419
```

```{r highways, echo = TRUE, include=FALSE, warning=FALSE, message=FALSE}
available_tags("highway")

highways <- sea %>% 
  opq() %>% 
  add_osm_feature(key = "highway",
                  value = c("motorway", "trunk", "primary", "secondary",
                            "tertiary", "motorway_link", "trunk_link",
                            "primary_link", "secondary_link", "tertiary_link")) %>% 
  osmdata_sf()

require(sf)
library(ggplot2)
ggplot() +
  geom_sf(data = highways$osm_lines,
          aes(color = highway),
          size = 0.2,
          alpha = 0.5) +
  theme_void()
```
```{r streets, echo = TRUE, include=FALSE, warning=FALSE, message=FALSE}
streets <- sea %>% 
  opq() %>% 
  add_osm_feature(key = "highway",
                  value = c("residential")) %>% 
  osmdata_sf()

ggplot() +
  geom_sf(data = streets$osm_lines,
          aes(color = highway),
          size = 0.2,
          alpha = 0.5) +
  theme_void()
```
```{r remove_color, echo = TRUE, include=FALSE, warning=FALSE, message=FALSE}
color_roads <- rgb(0.42, 0.449, 0.488)
ggplot() +
  geom_sf(data = streets$osm_lines,
          col = color_roads,
          size = 0.2,
          alpha = 0.5) +
  geom_sf(data = highways$osm_lines,
          col = color_roads,
          size = 0.2,
          alpha = 0.5) +
  coord_sf(xlim = c(min_lon, max_lon),
           ylim = c(min_lat, max_lat),
           expand = FALSE) +
  theme(legend.position = F) +
  theme_void()
```
```{r county_polygon, echo = TRUE, include=FALSE, warning=FALSE, message=FALSE}
require(tigris)
counties_WA <- counties(state = "WA",
                        cb = T,
                        class = "sf",)
counties_WA <- st_crop(counties_WA,
                       xmin = min_lon,
                       xmax = max_lon,
                       ymin = min_lat,
                       ymax = max_lat)

ggplot() +
  geom_sf(data = counties_WA, fill = "gray", lwd = 0) +
  coord_sf(xlim = c(min(sea[1,]),
                    max(sea[1,])),
           ylim = c(min(sea[2,]),
                    max(sea[2,])),
           expand = FALSE) +
  theme(legend.position = F) +
  theme_void()
```
```{r waterways, echo = TRUE, include=FALSE, warning=FALSE, message=FALSE}
get_water <- function(county_GEOID){
  area_water("WA", county_GEOID, class = "sf")
}

water <- do.call(rbind,
                       lapply(counties_WA$COUNTYFP, get_water))

water <- st_crop(water,
                 xmin = min_lon, xmax = max_lon,
                 ymin = min_lat, ymax = max_lat)

ggplot() +
  geom_sf(data = counties_WA) +
  geom_sf(data = water,
          inherit.aes = FALSE,
          col = "red") +
  coord_sf(xlim = c(min(sea[1,]),
                    max(sea[1,])),
           ylim = c(min(sea[2,]),
                    max(sea[2,])),
           expand = FALSE) +
  theme(legend.position = FALSE) +
  theme_void()
```
```{r accentuate_water, echo = TRUE, include=FALSE, warning=FALSE, message=FALSE}
st_erase <- function(x, y) {
  st_difference(x, st_union(y))
}

counties_WA <- st_erase(counties_WA, water)

ggplot() +
  geom_sf(data = counties_WA,
          lwd = 0) +
  coord_sf(xlim = c(min(sea[1,]), max(sea[1,])),
           ylim = c(min(sea[2,]), max(sea[2,])),
           expand = FALSE) +
  theme(legend.position = FALSE) +
  theme_void()
```
```{r black_yellow_theme, echo = TRUE, include=FALSE, warning=FALSE, message=FALSE}
ggplot() +
  geom_sf(data = counties_WA,
          inherit.aes = FALSE,
          lwd = 0.0,
          fill = rgb(0.203, 0.234, 0.277)) +
  coord_sf(xlim = c(min(sea[1,]), max(sea[1,])),
           ylim = c(min(sea[2,]), max(sea[2,])),
           expand = FALSE) +
  theme(legend.position = FALSE) +
  theme_void() +
  theme(panel.background = element_rect(fill = rgb(0.92, 0.679, 0.105))) +
  ggtitle("Dark & Yellow Theme")
```
```{r gray_white_theme, echo = TRUE, include=FALSE, warning=FALSE, message=FALSE}
ggplot() + 
  geom_sf(data=counties_WA,
          inherit.aes= FALSE,
          lwd=0.0,fill="white")+
  coord_sf(xlim = c(min(sea[1,]), max(sea[1,])), 
         ylim = c(min(sea[2,]), max(sea[2,])),
         expand = FALSE)+
  theme(legend.position = F) + 
  theme_void()+
  theme(panel.background=
          element_rect(fill = rgb(0.9,0.9,0.9)))+
  ggtitle("Gray + White theme")
```
```{r black_white_theme, echo = TRUE, include=FALSE, warning=FALSE, message=FALSE}
ggplot() + 
  geom_sf(data=counties_WA,
          inherit.aes= FALSE,
          lwd=0.0,fill=rgb(0.95,0.95,0.95)) +
  coord_sf(xlim = c(min(sea[1,]), max(sea[1,])), 
         ylim = c(min(sea[2,]), max(sea[2,])),
         expand = FALSE)+
  theme(legend.position = F) + 
  theme_void() +
  theme(panel.background=element_rect(fill = "black")) +
  ggtitle("White + Black theme")
```
```{r add_Streets, echo = TRUE, include=FALSE, warning=FALSE, message=FALSE}
p_sea<- ggplot() + 
  geom_sf(data=counties_WA,
          inherit.aes= FALSE,
          lwd=0.0,fill=rgb(0.203,0.234,0.277)) +
  geom_sf(data = streets$osm_lines,
          inherit.aes = FALSE,
          color=color_roads,
          size = .2,
          alpha = .5) +
  geom_sf(data = highways$osm_lines,
          inherit.aes = FALSE,
          color=color_roads,
          size = .2,
          alpha = .5) +
  coord_sf(xlim = c(min(sea[1,]), max(sea[1,])), 
           ylim = c(min(sea[2,]), max(sea[2,])),
           expand = FALSE) +
  theme(legend.position = F) + theme_void() +
  theme(panel.background=
          element_rect(fill = "#0A7682"))

p_sea

ggsave("seattlev3.pdf")
```
```{r add_personal_routes, echo=TRUE, include=FALSE, warning=FALSE, message=FALSE}
library(readr)
require(osrm)
require(data.table)
locs.sites <- read_csv("~/Desktop/Coding Projects/Maps/Maps 2021 - Seattle.csv")
View(locs.sites)

locs.sites$time <- as.Date(locs.sites$time)
class(locs.sites$time)

daily_routes <- function(date) {
  ll <- locs.sites[as.Date(time)==date, c("lon", "lat")]
  #add home early in the morning 	
  ll <- rbind(data.table(lon = -122.3610036, lat = - 47.6646144), ll)
  #add home late in the day
  ll <- rbind(ll, data.table(lon = -122.3610036, lat = 47.6646144))
  route <- NULL
  for (j in 2:nrow(ll)) {
    p1 <- c(ll$lon[j-1], ll$lat[j-1])
    p2 <- c(ll$lon[j], ll$lat[j])
    oo <- osrmRoute(src = p1, dst = p2, returnclass = "sf",
                    overview = "full")
    route <- rbind(route, oo)
  }
  route
}

dates <- unique(as.Date(locs.sites$time))
routes <- do.call(rbind(
                  lapply(dates), daily_routes))

# Error in do.call(rbind(lapply(dates), daily_routes)) : 
#  argument "args" is missing, with no default
```

```{r final_map }
final_map <- ggplot() + 
  geom_sf(data=counties_WA,
          inherit.aes= FALSE,
          lwd=0.0,fill=rgb(0.203,0.234,0.277))+
  geom_sf(data = streets$osm_lines,
          inherit.aes = FALSE,
          color=color_roads,
          size = .2,
          alpha = .5) +
  geom_sf(data = highways$osm_lines,
          inherit.aes = FALSE,
          color=color_roads,
          size = .2,
          alpha = .5) +
  geom_sf(data=st_geometry(routes),
          inherit.aes = FALSE,col="red",alpha=0.5)+ 
  coord_sf(xlim = c(min(sea[1,]), max(sea[1,])), 
           ylim = c(min(sea[2,]), max(sea[2,])),
           expand = FALSE) +
  theme(legend.position = F) + theme_void()+
  theme(panel.background=
          element_rect(fill=rgb(0.92,0.679,0.105)))
final_map
```

```{r final_printing}
#ggsave(final_map, 
#       filename = "seattle.png",
#       scale = 1, 
#       width = 36, 
#       height = 24, 
#       units = "in",
#      dpi = 500)
```

